-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 07:07:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musiverse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musiverse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musiverse` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `musiverse` ;

-- -----------------------------------------------------
-- Table `musiverse`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`artista` (
  `id_artista` INT NOT NULL AUTO_INCREMENT,
  `nombre_artista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_artista`),
  UNIQUE INDEX `nombre_artista` (`nombre_artista` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musiverse`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `id_artista` INT NOT NULL,
  `ano_lanzamiento` YEAR NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `id_artista` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `id_artista`
    FOREIGN KEY (`id_artista`)
    REFERENCES `musiverse`.`artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musiverse`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`cancion` (
  `id_cancion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `duracion` TIME NOT NULL,
  `genero` VARCHAR(50) NULL DEFAULT NULL,
  `id_album` INT NOT NULL,
  `id_artista` INT NOT NULL,
  PRIMARY KEY (`id_cancion`),
  INDEX `id_album` (`id_album` ASC) VISIBLE,
  INDEX `id_artista` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `id_album`
    FOREIGN KEY (`id_album`)
    REFERENCES `musiverse`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_artista`
    FOREIGN KEY (`id_artista`)
    REFERENCES `musiverse`.`artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musiverse`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_electronico` (`correo_electronico` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musiverse`.`lista_reproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`lista_reproduccion` (
  `id_lista_reproduccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_lista` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_lista_reproduccion`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `musiverse`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musiverse`.`cancion_lista_reproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiverse`.`cancion_lista_reproduccion` (
  `id_cancion` INT NOT NULL,
  `id_lista_reproduccion` INT NOT NULL,
  PRIMARY KEY (`id_cancion`, `id_lista_reproduccion`),
  INDEX `id_lista_reproduccion` (`id_lista_reproduccion` ASC) VISIBLE,
  CONSTRAINT `id_cancion`
    FOREIGN KEY (`id_cancion`)
    REFERENCES `musiverse`.`cancion` (`id_cancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_lista_reproduccion`
    FOREIGN KEY (`id_lista_reproduccion`)
    REFERENCES `musiverse`.`lista_reproduccion` (`id_lista_reproduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
